name: Upload and Cleanup Artifacts

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test.txt
        run: echo "This is a test file." > test.txt

      - name: Upload test.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Artifacts
        run: |
          # Use GitHub API to delete artifacts
          RUN_ID=${{ github.run_id }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          curl -X "POST" -H "Authorization: Bearer $TOKEN" \
          "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID/artifacts" \
          -d "{}"
