# .github/workflows/main.yml

name: My CI/CD Workflow

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  strategy_job:
    name: Create Strategy Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Feature Folder Contents
        run: |
          echo "Checking contents of the feature folder..."
          ls ${{ inputs.feature_folder }}

      - name: Create JSON files
        run: |
          # Create an empty array to store strategy objects
          strategies=()

          # Calculate the number of strategies (5 or 3) based on the total file count
          total_files=$(find ${{ inputs.feature_folder }} -type f -name "*.feature" | wc -l)
          if [[ $total_files -gt 10 ]]; then
            strategies=5
          elif [[ $total_files -gt 3 ]]; then
            strategies=3
          else
            strategies=1
          fi

          # Calculate the maximum number of files per strategy
          max_files_per_strategy=$(( (total_files + strategies - 1) / strategies ))

          # Loop through the strategies and add each strategy object to the array
          for strategy in $(seq 1 $strategies); do
            feature_files=($(find ${{ inputs.feature_folder }} -type f -name "*.feature" | head -n $max_files_per_strategy))
            max_files_per_strategy=$(( max_files_per_strategy - ${#feature_files[@]} ))

            # Create the strategy object and add it to the array
            strategy_object="{\"name\": \"Shard $strategy\", \"strategy\": \"Cucumber\", \"values\": {\"features\": $(echo ${feature_files[@]} | jq -R . | jq -s .)}}"
            strategies+=("$strategy_object")
          done

          # Construct the JSON output with the strategies array
          json="{"

          # Include the devices block if devices are provided
          if [ "${{ inputs.device_list }}" != "none" ]; then
            json+="\"devices\": [${{ inputs.device_list }}], "
          fi

          # Add additional keys outside the shard block
          json+="\"project\": \"${{ inputs.project }}\", \"custom_id\": \"${{ inputs.custom_id }}\", "

          json+="\"strategies\": $(echo ${strategies[@]} | jq -s .), "  # Strategies array

          json+="\"numberOfShard\": $strategies, "  # Number of strategies
          json+="\"deviceSelection\": \"any\""   # Device selection

          json+="}"

          # Save JSON to a file named config.json in the .github folder
          echo "$json" > .github/config.json

      - name: Show Config JSON
        run: cat .github/config.json
