name: Upload and Cleanup Artifacts

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Repo Variable
        run: echo variable - ${{ vars.FILE_PATH }}


  demo:
    name: Demo
    uses: ./.github/workflows/test.yml
    with:
      input_text: ${{ vars.FILE_PATH }}
