name: Upload and Cleanup Artifacts

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Repo Variable
        run: echo variable - ${{ vars.FILE_PATH }}
      - name: Set Outputs
        id: test
        uses: ./.github/actions/test-output

      - name: Use Output
        run: |
          echo "Task: $TASK_OUTPUT"
          echo "Blocks: ${{  env.BLOCKS_OUTPUT }}"
          echo "New: ${{  env.TASK_OUTPUT }}"
          echo "Old: ${{  steps.test.outputs.sample }}"
          echo "New 2: ${{  steps.test.outputs.sum }}"
          echo "New - 1: ${{  steps.test.outputs.test-data }}"

  demo:
    name: Demo
    uses: ./.github/workflows/test.yml
    with:
      input_text: ${{ vars.FILE_PATH }}
