jobs:
  encrypt_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Set up code
        uses: actions/checkout@v2

      - name: Encrypt secret using OpenSSL
        id: encrypt
        run: |
          # Encrypt using AES-256-CBC and a passphrase
          ENCRYPTED_SECRET=$(echo -n "Secret data" | openssl enc -aes-256-cbc -e -base64 -pass pass:yourpassphrase)
          echo "ENCRYPTED_SECRET=$ENCRYPTED_SECRET" >> $GITHUB_ENV

      - name: Show encrypted secret
        run: echo $ENCRYPTED_SECRET