name: Upload and Cleanup Artifacts

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      - name: Install Dependencies
        run: npm install
      - name: Print Repo Variable
        run: echo variable - ${{ vars.FILE_PATH }}
      - name: Set Outputs
        id: test
        uses: ./.github/actions/test-output

      - name: Use Output
        run: |
          
          echo "New - 1: ${{  steps.test.outputs.test_data }}"

  demo:
    name: Demo
    uses: ./.github/workflows/test.yml
    with:
      input_text: ${{ vars.FILE_PATH }}
