name: Generate Strategy JSON

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Determine Number of Strategies
        id: num_strategies
        run: |
          max_files_per_strategy=3
          total_files=$(find $FEATURE_FOLDER -name "*.feature" -type f | wc -l)
          num_strategies=$((total_files / max_files_per_strategy))
          if ((total_files % max_files_per_strategy > 0)); then
            num_strategies=$((num_strategies + 1))
          fi
          echo "::set-output name=num_strategies::$num_strategies"

      - name: Create JSON File
        id: create_json
        run: |
          max_files_per_strategy=3
          total_files=$(find $FEATURE_FOLDER -name "*.feature" -type f | wc -l)
          num_strategies=${{ steps.num_strategies.outputs.num_strategies }}

          strategyList="[
          "
          strategyCounter=1
          currentStrategy=""

          find $FEATURE_FOLDER -name "*.feature" -type f | while read -r fileName; do
            if [ $(( strategyCounter % max_files_per_strategy )) -eq 1 ]; then
              if [ $strategyCounter -gt 1 ]; then
                strategyList+=$(echo $currentStrategy | jq -c .)
                strategyList+=","
              fi
              currentStrategy="{\"name\": \"Strategy - $strategyCounter\", \"strategy\": \"Cucumber\", \"values\": {\"features\": [\"$fileName\""
            else
              currentStrategy+=",\"$fileName\""
            fi
            strategyCounter=$((strategyCounter + 1))
          done
          currentStrategy+="]}}"
          strategyList+=$(echo $currentStrategy | jq -c .)
          strategyList+="]"

          # Save JSON to a file named config.json in the .github folder
          echo "$strategyList" > .github/config.json

      - name: Show Config JSON
        run: cat .github/config.json
