# .github/workflows/main.yml

name: My CI/CD Workflow

on:
  push:
    branches:
      - '*' # Run on every push to any branch
  pull_request:

jobs:
  strategy_job:
    name: Create Strategy Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the Feature Scanner action
        id: config
        uses: ./.github/actions/create_config
        with:
          feature_folder: 'app/src/androidTest/assets/features'
          project_name: ${{ github.repository }}
          device_list: '["device1","device2","device3"]'
          tag_name: 'v1.0'
          custom_id: 'Sample Custom ID'

      - name: Verify
        run: |
          echo Total Files: ${{ steps.config.outputs.totalFiles }}
          echo No of Blocks: ${{ steps.config.outputs.blocks }}
          echo File Per Block: ${{ steps.config.outputs.filesPerBlock }}
          echo Config: ${{ steps.config.outputs.config_json }}
          echo ${{ steps.config.outputs.config_json }} > config.txt

      - name: Publish Config
        uses: actions/upload-artifact@v3
        with:
          name: Config File
          path: ./config.txt




