name: Upload and Cleanup Artifacts

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Repo Variable
        run: echo variable - ${{ vars.FILE_PATH }}
      - name: Set Outputs
        uses: ./.github/actions/test-output

      - name: Use Output
        run: |
          echo "Task: $TASK_OUTPUT"
          echo "Blocks: ${{  env.BLOCKS_OUTPUT }}"

  demo:
    name: Demo
    uses: ./.github/workflows/test.yml
    with:
      input_text: ${{ vars.FILE_PATH }}
