# .github/workflows/main.yml

name: My CI/CD Workflow

on:
  push:
    branches:
      - '*' # Run on every push to any branch
  pull_request:

jobs:
  strategy_job:
    name: Create Strategy Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Feature Folder Contents
        run: |
          echo "Checking contents of the feature folder..."
          ls ${{ inputs.feature_folder }}

      - name: Create JSON files
        run: |
          # Create an empty array to store strategy objects
          strategies=()

          # Calculate the number of strategies (5 or 3) based on the total file count
          total_files=$(find ${{ inputs.feature_folder }} -type f -name "*.feature" | wc -l)
          if [[ $total_files -gt 10 ]]; then
            strategies=5
          elif [[ $total_files -gt 3 ]]; then
            strategies=3
          else
            strategies=1
          fi

          # Calculate the number of files for each strategy and the remaining files
          files_per_strategy=$(( total_files / strategies ))
          remaining_files=$(( total_files % strategies ))

          # Loop through the strategies and add each strategy object to the array
          start_idx=1
          for strategy in $(seq 1 $strategies); do
            # Calculate the end index for this strategy
            end_idx=$(( start_idx + files_per_strategy - 1 + (strategy <= remaining_files ? 1 : 0) ))

            # Get the feature files for this strategy
            feature_files=($(find ${{ inputs.feature_folder }} -type f -name "*.feature" | head -n $end_idx | tail -n +$start_idx))

            # Convert feature_files array to a comma-separated string
            files_string=$(printf "\"%s\"," "${feature_files[@]}")
            files_string=${files_string%,}  # Remove the trailing comma

            # Create the strategy object and add it to the array
            strategy_object="{\"name\": \"Shard $strategy\", \"strategy\": \"Cucumber\", \"values\": {\"features\": [$files_string]}}"
            strategies+=("$strategy_object")

            # Update the start index for the next strategy
            start_idx=$(( end_idx + 1 ))
          done

          # Construct the JSON output with the strategies array
          json="{"

          # Include the devices block if devices are provided or use a default value
          if [ -n "${{ inputs.device_list }}" ]; then
            json+="\"devices\": [${{ inputs.device_list }}], "
          else
            json+="\"devices\": [\"device1\", \"device2\"], "  # Default device list
          fi

          # Add additional keys outside the shard block
          json+="\"project\": \"${{ inputs.project }}\", \"custom_id\": \"${{ inputs.custom_id }}\", "

          json+="\"mapping\": $(
            echo "${strategies[@]}" | jq -s '.'  # Convert strategies array to JSON
          ), "

          json+="\"numberOfShard\": $strategies, "  # Number of strategies
          json+="\"deviceSelection\": \"any\""   # Device selection

          json+="}"

          # Save JSON to a file named config.json in the .github folder
          echo "$json" > .github/config.json

      - name: Show Config JSON
        run: cat .github/config.json
