name: Upload and Cleanup Artifacts

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Repo Variable
        run: echo variable - ${{ vars.FILE_PATH }}
      - name: Set Outputs
        id: test
        uses: ./.github/actions/test-output

      - name: Use Output
        run: |
          
          echo "New - 1: ${{  steps.test.outputs.test_data }}"
          echo "Test - 1: ${{  steps.test.outputs.test_data1 }}"
          echo "The output is $MY_OUTPUT_NAME"

  demo:
    name: Demo
    uses: ./.github/workflows/test.yml
    with:
      input_text: ${{ vars.FILE_PATH }}
